###
GET http://localhost:3001/api/users/

###
GET http://localhost:3001/api/users/1

###
DELETE  http://localhost:3001/api/users/4

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "firstName": "Johnny", 
    "lastName": "Tejada", 
    "birthday": "2000-07-03", 
    "email": "example@gmail.com", 
    "password": "12345", 
    "quote": "Lets make today a memorable one!",
    "profilePic": ""
}

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "firstName": "John", 
    "lastName": "Smith", 
    "birthday": "1999-05-10", 
    "email": "example1@gmail.com", 
    "password": "123456", 
    "quote": "Hey there, lets travel together!!",
    "profilePic": "https://randomuser.me/api/portraits/men/1.jpg"
}

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "firstName": "Michael", 
    "lastName": "Jordan", 
    "birthday": "1969-08-20", 
    "email": "example2@gmail.com", 
    "password": "1234", 
    "quote": "Make the world a better place!",
    "profilePic": "https://randomuser.me/api/portraits/men/9.jpg"
}

###
PATCH  http://localhost:3001/api/users/2
Content-Type: application/json

{
    "firstName": "John", 
    "lastName": "Smith", 
    "birthday": "1999-05-10", 
    "email": "example1@gmail.com", 
    "password": "123456", 
    "quote": "Hey there, lets travel together!!",
    "profilePic": "https://randomuser.me/api/portraits/men/1.jpg"
}

###
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "12345"
}


###
GET http://localhost:3000/api/posts/

###
GET http://localhost:3000/api/posts/1

###
DELETE  http://localhost:3000/api/posts/9

###
POST http://localhost:3000/api/posts/
Content-Type: application/json

{
    "img": "https://images.unsplash.com/photo-1516098455581-e8d9a8f8d7e0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
    "caption": "Testing",
    "adventureID": 2
}

###
PATCH  http://localhost:3000/api/posts/9
Content-Type: application/json

{
    "caption": "updated caption"
}



###
GET http://localhost:3001/api/friends/

###
GET http://localhost:3001/api/friends/3

###
DELETE  http://localhost:3000/api/friends/3

###
DELETE  http://localhost:3001/api/friends/email/cbrown@gmail.com/example@gmail.com

###
POST http://localhost:3001/api/friends/3/example1@gmail.com

###
POST http://localhost:3000/api/friends/
Content-Type: application/json

{
    "friends": ["example@gmail.com"]
}

###
POST http://localhost:3001/api/friends/cbrown@gmail.com/example@gmail.com



###
GET http://localhost:3001/api/stops/

###
GET http://localhost:3000/api/stops/3

###
DELETE  http://localhost:3001/api/stops/1

###
POST http://localhost:3000/api/stops/
Content-Type: application/json

{
    "location": "New York",
    "img": "https://images.unsplash.com/photo-1582436416930-f533b50a7cd8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=436&q=80",
    "adventureID": 5
}

###
PATCH  http://localhost:3000/api/stops/9
Content-Type: application/json

{
    "adventureID": 1
}
